<?php
$year = '1988';

$heading = <<<'HTML'
Ševeček, Ludvík:  <em>Painting as a means for essential communication</em><br/>
Not published text, 1988, author archive
HTML;

$content = <<<'HTML'

<p>Collaboration between the Regional Gallery of Fine Arts in Zlín and the painter Oldřich Tichý, who was born in Zlín, dates from the end of the 1980s, when the gallery acquired one of Tichý’s key early works, I Run in the Fields (1989). In 1993 it was one of the first state-run galleries in the Czech Republic to hold an exhibition of Tichý’s paintings.<sup>1</sup> Since then Tichý’s work has appeared regularly in the gallery’s permanent exhibition of twentieth-century Czech art, and in all major group exhibitions and exhibitions of contemporary Czech art that the gallery has held, especially the New Zlín Salon exhibitions.<sup>2</sup> All of that collaboration has now logically resulted in an extensive retrospective exhibition of Tichý’s work, including many of his key works from 1980–2006.<sup>3</sup> In addition to paintings, there are also less well-known objects from 1995, which are very important in the context of his work. However, when planning the exhibition the main emphasis has been on his remarkable work from recent years, represented at the exhibition by his major paintings and a smaller collection of contemporary works on paper, which are not included in the catalogue.</p>
<p>Oldřich Tichý is one of the artists who appeared on the Czech art scene in the 1980s, one of a generation of artists in which the ambitious members of the Tvrdohlaví group were prominent during the years of totalitarianism. They were not however the only ones; their uniquely direct path to the art scene was provocative at the time, but there were other artists working in isolation who rose to prominence without being part of a collective, artists who were more inward-looking, and often displayed a respect for the art of earlier generations, and for nature and the mysterious aspects of human existence. That characterises the life and art of Oldřich Tichý, who went from the Zlín region to study in Prague in 1980, after attending the The Secondary School of Applied Art in Uherské Hradiště and spending two years working as an art therapist at a psychiatric hospital in Kroměříž. However, the situation at the Academy of Fine Arts in Prague in the 1980s, and the studio of Professor František Ji­roudek, did not conform to Tichý’s ideas on how art should be studied, something he was preoccupied with at the time. The young artist’s attempts to arrive at an individual conception for his art, which was now emerging in his first significant paintings, contrasted substantially with ideas on teaching at the Academy, and differed entirely from the paintings of his professor. However, despite those difficulties, Oldřich Tichý was able to devote himself to his art with his characteristic tenacity.<sup>4</sup> Initially he continued working on expressive figurative compositions in the style of Rouault, inspired by his experience of working at the psychiatric hospital. Those works indicate his interest at the time in extreme mental states. A certain shift in his ideas is evident in his imaginative still lifes (1986–87), which verge on the abstract, and despite continuing with a great number of forms and dynamic brushwork, they established a trend towards the clarification of forms, making them monumental and crystalline, which was important for subsequent developments in his painting. We can date the beginning of Tichý’s life as an artist to around 1980. Around 1983, new themes appear in his work (Morning, Wedding . . .), and his style becomes more relaxed. The first still lifes from his studio (1986) are painted in a similar style, but, with the emphasis on the constructive aspect of forms, the still lifes are gradually transformed from detailed studies into more general forms, and in accordance with that the colour aspects of a composition become more important. It is an imaginative plastic and spatial conception of abstract subject matter, free of illusory direct ties to the outer world. Those still lifes (1987) are now entirely autonomous, independent of visual reality, emancipated and purely aesthetic entities with psychological significance, and their poetry draws on symbolism of an existential scope (Memory of Childhood, In the Same Boat — both 1987).</p>
<p>That entire introductory period, the search for a form in painting that corresponded to the artist’s nature, came to fruition in 1988–89. A more or less straight line leads from the paintings he produced at that time to his present compositions, with the essential diversions resulting from the broad scope and exploratory nature of his work. In 1988 Tichý painted a series of canvasses based on a direct conception of themes drawn from objective and natural phenomena in the external world. The surreal, expressionist syntheses of his earlier abstract compositions, reminiscent of František Janoušek, were greatly transformed by this new approach to inner and outer reality. There are paintings with powerful details and symbols from the visual world, which are simultaneously, in the choice and way of seeing the motif, attributes of man’s presence in that world. They are the currency of the artist’s existential experience of the world, in the profundity of its duration, its immutability, and in the open dynamism of the phenomena of life and art, cosmic events and the rhythms of nature. These robust, colourful and masterfully executed forms from the real world are an integral part of the imaginary space of a painting, with which they comprise a unity, a polyphonic archetype of symbolist scope, with layers of meaning. That can clearly be seen in compositions such as I Live Alone in the Woods Here (1988), I Run in the Fields (1989), and I am House and Tree (1989), in which the intuitive search for identity and the natural order of man and nature in the pragmatic world of post-industrial civilisation and the increasing atomisation of human existence are magnified by the artist’s distinctive personalisation of the motif, his “essentially personal themes”.</p>
<p>Tichý continued to work on those subjects for the following decade. His quest for a more profound and more powerful expression of his essential themes and the general psychological themes of the time led him to pay greater attention to the formal aspects of painting, which later resulted</p>
<p>in clearly formulated compositions, alongside the colouristic aspects of his style, and in inventive work with surface and space. In addition to the traditional themes from his earlier period, this new trend brought a number of entirely new motifs and motivations to his work. Particularly important in that respect is a series of paintings with titles that are characteristically psychological, but also based on space and subject matter: Window and Window into You (1994). 1995 was however an exceptional year in Tichý’s work, during which he produced an entire series of hanging objects (Gate, Wind, Closed for Eternity). They are in essence utilitarian objects associated with traditional rural life and work, but he has elevated them, without significant formal alterations, to the level of art. Those objects are an expression and symbol of the artist’s close ties to nature and the countryside, where he now lives, but they also in some sense conclude the preceding chapter in his work, and anticipate his paintings in the years that followed.</p>
<p>That is evident in canvasses such as Hiding Places (1998), or a series of paintings of windows, from Window into You V (1995) to Window (2001). The personification of the objective aspects of existence lends greater significance to the duality of the conception of the motifs depicted, which is particularly powerful in paintings from recent years, and in his current work. The theme of the duality of the inner (spiritual) and outer (atomised, material) worlds is captured in a remarkable organic unity with all of his earlier work. In Oldřich Tichý’s paintings, Me and You, reminiscent of Buber’s I and Thou, is not just the title of a specific painting (2006), which is included in the exhibition, but it has a more general validity in the context of his oeuvre as a whole.<sup>5</sup> That “philosophical” theme is present in a particularly clear form in Tichý’s current work. One of the typical compositions produced in that spirit is A Path in the Labyrinth (2001–06), where “Me” — a clear element in the form of a massive and illusive wooden cross, depicted in a diagonal (dramatisation) in the foreground, while the background is chaotically abstract, some kind of symbol of the outer world, an attribute of chaos or of atomised existence. The cross as a symbol of man (the human figure) is the main subject of another important painting, Lying (2004). In that painting, the background is a relatively tranquil unified field, compact in its colour and form. There are other remarkable compositions, based on a spatial two-dimensionality, which draw on the tension between the specific and the indefinite (or abstract), such as Just above the earth in one move (2005), or paintings evoking an existential, poetic perception of the world (There, behind you, is the night, 2002, Two Angels, 2005). Night (2006) is another of Tichý’s current paintings that use an abstract form to present a kind of Baroquely spiritual experience of the eternal, which is inherent in the artist’s approach to the world, albeit one censured by the pragmatism of contemporary attitudes to life. It is evident that painting has become for him a crucial device for essential communication. With his intense vision of the theme, he presents what a casual glance does not reveal, yet which exists as something that is central: the spiritual substance of our lives, the fundamental integrating element of human existence.</p>

<hr/>

<p><sup>1</sup> oldřich tichý, Paintings, Zlín State Gallery, foyer of Zlín Theatre, 1993 (introduction in the catalogue by Jana Šálková).</p>
<p><sup>2</sup> In addition to exhibitions of new acquisitions and various permanent exhibitions at the gallery, Oldřich Tichý’s work was included in the exhibition Contemporary Art — The 90s in the Zlín House of Arts, held by the Zlín State Gallery in 1995, and at all four triennial New Zlín Salon exhibitions (1996, 1999, 2002, 2005).</p>
<p><sup>3</sup> Several important works, especially earlier works, are at present out of the artist’s reach, for the most part in private collections abroad, and therefore could not be included in the exhibition.</p>
<p><sup>4</sup> The atmosphere at the Academy of Fine Arts in Prague in the 1980s was evidently none too liberal. Oldřich Tichý recalls his studies there disdainfully: “I began with figures, and by the fourth year I was painting abstract paintings. The teaching staff didn’t like that much, so they made me do the classic disciplines — the nude, the portrait, the landscape and the still life, which I ultimately chose for my subsequent work . . .”.</p>
<p>There are no accidents, an interview with oldřich tichý by radan wagner in Já a Ty. Katalog výstavy Oldřicha Tichého, Galerie Václava Špály v Praze, 1993.</p>
<p><sup>5</sup> In 2003 the most important exhibition of Tichý’s work was held under the title Me and You at the Václav Špála Gallery in Prague. See note no. 4.</p>

HTML;
