<?php
$year = '2014';

$heading = <<<'HTML'
Ševeček, Ludvík:  <em>Malba jako prostředek bytostné komunikace</em><br/>
Nepublikovaný text, 1988, archiv autora
HTML;

$content = <<<'HTML'

<p>Spolupráce Krajské galerie výtvarného umění ve Zlíně se zlínským rodákem, malířem Oldřichem Tichým započala na sklonku osmdesátých let minulého století, kdy instituce získala do sbírek jednu z jeho podstatných raných obrazových kompozic Běžím v polích (1989). Již v roce 1993 mu také jako jedna z prvních státních galerií u nás uspořádala výstavu obrazové tvorby<sup>1</sup>. Od té doby se autorovy práce objevovaly ve výstavních prostorách instituce pravidelně. Nejen ve stálé expozici českého umění 20. století ze sbírek galerie, ale zejména v instalacích všech významných kolektivních výstav a přehlídek soudobého českého umění, jež uskutečňovala, především v expozicích Nového zlínského salonu.<sup>2</sup> Celá předchozí spolupráce nyní logicky vyústila v uspořádání rozsáhlé retrospektivní přehlídky autorova díla, která zahrnuje řadu jeho podstatných prací z let 1980–2006.<sup>3</sup> Vedle obrazů jsou to i méně známé, nicméně v kontextu jeho tvorby velmi důležité objekty z roku 1995. Hlavní důraz byl ale při koncipování přehlídky kladen především na jeho pozoruhodně se rozvíjející tvorbu posledních let, zastoupenou v instalaci výstavy nejenom zásadními obrazy, ale i menším souborem současných prací na papíře mimo katalog.</p>
<p>Oldřich Tichý náleží k autorům, kteří nastupovali na českou uměleckou scénu v osmdesátých letech uplynulého století, ke generaci tvůrců, z nichž se za totality zviditelnili zejména ambiciózní členové skupiny Tvrdohlavých. Nebyli to však pouze oni, jejich v tehdejších kulturních poměrech až provokující, exkluzivně přímočará cesta na výsluní veřejné výtvarné scény, ale i další po výtce solitérní osobnosti, jež do popředí pronikaly z méně „kolektivních“ pozic, více u sebe, nezřídka v respektu k umění předchozích generací, ale i v respektu k přírodě a tajemným stránkám lidského bytí. Právě tyto rysy už od samotných počátků charakterizují také životní a umělecký postoj Oldřicha Tichého, který se vydal na studia do Prahy ze zlínského regionu v roce 1980, po ukončení supš v Uherském Hradišti a dvouleté práci arteterapeuta v psychia­trické léčebně v Kroměříži. Situace na pražské akademii v osmdesátých letech — včetně ateliéru prof. Františka Jiroudka, do něhož byl přijat — však příliš nekonvenovala s jeho představami o studiu umění, jemuž se v té době již cílevědomě věnoval. Snaha mladého adepta umění o vlastní výtvarné pojetí, jež se již zračila v prvních jeho závažnějších malířských projevech, značně kontrastovala s trendem akademické výuky a rozcházela se zcela i s malbou jeho profesora. Se sobě vlastní houževnatostí se však Oldřich Tichý dokázal i za ztížených podmínek věnovat vlastní tvorbě.<sup>4</sup> Zprvu pokračoval v promýšlení a rozvíjení svých expresívních figurálních kompozic „rouaultovské ražby“, podnícených předchozími zkušenostmi z práce v psychiatrické léčebně. Ty poukazují zejména na tehdejší jeho zaujetí mezními psychickými stavy lidské bytosti. Určitý názorový posun je patrný v imaginativních zátiších inklinujících až k abstrakci (1986–1987), která i přes pokračující mnohost forem a dynamický malířský rukopis již nastolují z hlediska dalšího rozvoje jeho malby důležitý trend k určitému zjasnění tvarů, k jejich monumentalizaci a krystalizaci. Souhrnně lze konstatovat, že autorovy umělecké počátky spadají do doby kolem roku 1980. Přibližně v roce 1983 se u něho objevují nová témata (Ráno, Svatba . . .) a jeho projev se malířsky uvolňuje. Zprvu v obdobném malířské dikci vznikají v umělcově ateliéru i první zátiší (1986). S důrazem kladeným na stavebnost forem však docházelo k jejich postupné transformaci od věcnosti k obecněji založeným tvarům a v souladu s tím se prohloubila i barevná stránka kompozice. Jde o po výtce imaginativní plasticko-prostorové pojetí abstraktního tématu, bez přímých iluzívních vazeb k vnějšímu světu. Tato zátiší (1987) jsou již zcela autonomní — na vizuální realitě nezávislé, emancipované, ryze estetické entity s přesahujícími psychologickými významy — jejich poezie těží ze symboliky existenciálního dosahu (Vzpomínka na dětství, Na jedné lodi — oba 1987).</p>
<p>Celé toto úvodní tvůrčí údobí, odehrávající se ve znamení hledání malířského tvaru adekvátního autorovu uměleckému naturelu, se svým způsobem naplňovalo v letech 1988–1989. Od obrazů, které v tom čase vytvořil, také vede, i přes nezbytná vybočení, daná šíří záběru či průzkumným charakterem jeho tvorby, v podstatě přímá cesta až ke kompozicím současným. Již v roce 1988 umělec vytvořil řadu pláten založených na bezprostředním, bytostném pojetí témat vytavených z předmětných a přírodních souvislostí vnějšího světa. Surrealisticko-expresionistický syntetismus předchozích abstraktních kompozic, upomínajících na Františka Janouška, se tímto novým vztahem k vnitřní i vnější realitě podstatným způsobem transformoval. Jde o obrazy s monumentálně cítěnými věcnými prvky a znaky vizuálního světa, jež jsou ale současně — výběrem a způsobem vidění motivu — atributy přítomnosti člověka v něm. Jsou devízou umělcova existenciálně založeného prožitku světa, jak v hloubce jeho trvání a neměnnosti, tak i v jeho otevřenosti dynamice jevů života a kultury, vesmírných dějů a rytmů přírody. Tyto robustně, koloristicky a rukopisně bravurně budované tvary reálného světa jsou integrální součástí imaginárního obrazového prostoru, s nímž tvoří jednotu — významově vrstevnatý polyfonní archetyp značného symbolistního dosahu. Zřetelným dokladem toho jsou zejména obrazové kompozice typu Žiju sám ve zdejších lesích (1988), Běžím v polích (1989) anebo Jsem domem i stromem (1989), v nichž intuitivní hledání identity, přirozeného řádu člověka a přírody v pragmatickém světě postindustriální civilizace s narůstající atomizací lidského bytí, ještě umocňuje zvláštní autorská personalizace motivu, jeho „bytostně osobnostní tematizace“.</p>
<p>V intencích tohoto trendu se umělcova tvorba rozvíjela i v průběhu následného desetiletí. Snaha o hlubší a působivější, lapidární vyjádření vlastních bytostných a vůbec psychologických dobových témat obrátila jeho pozornost ve zvýšené míře k formálním aspektům obrazu, jež posléze vyústila v malířsky jasně formulovaných kompozicích, postavených vedle koloristických kvalit projevu, hlavně na invenční práci s plochou a prostorem. Kromě tradičních námětů známých už z předchozího období se v souvislosti s uvedeným trendem v jeho tvorbě objevily i některé zcela nové motivy či motivace. Důležitá v tomto ohledu je především řada obrazů s příznačnými psychologizujícími, ale i prostorově a předmětně motivovanými názvy Okno a Okno do tebe (1994). Výjimečný v kontextu autorovy tvorby však byl hlavně rok 1995, v jehož průběhu vytvořil celou sérii závěsných objektů (Brána, Vítr, Zavřeno na věky). Jedná se v podstatě o užité předměty spjaté s životem a tradičními činnostmi venkova, jež jsou v jeho redakci, bez výraznějších formálních změn povýšeny do umělecké roviny. Tyto objekty jednak vyjadřují a symbolizují autorovy úzké vazby s venkovským a přírodním prostředím, v němž trvale žije, jednak v jistém smyslu uzavírají i předchozí kapitolu jeho tvorby a svým charakterem na straně druhé současně předjímají i jeho malbu let následných.</p>
<p>Dokládají to plátna jako Úkryty (1998) anebo celá řada obrazů na téma okno, počínaje Oknem do tebe V. (1995) až po Okénko (2001). Personifikací věcných stránek bytí nabývá na významu dualita pojetí ztvárněných motivů, zvláště působivá v autorově malbě posledních let, ale i v tvorbě současné. Téma duality vnitřního (duchovního) a vnějšího (atomizovaného, materiálního) světa je v jejím rámci postiženo v pozoruhodné organické jednotě s celým jeho předchozím dílem. Ono „buberovské“ Já a Ty tak v souvislosti s malbou Oldřicha Tichého není jen názvem jednoho konkrétního současného obrazu (2006), zařazeného do souboru naší výstavy, ale má obecnější platnost v kontextu celé jeho tvorby.<sup>5</sup> Ve zvláště vyhraněné podobě je toto „filosofické“ téma přítomno hlavně v umělcově malbě nejsoučasnější. Jednou z charakteristických kompozic vytvářených v tomto duchu je např. V labyrintu cesta (2001–2006), kde „Já“ — jasný prvek v podobě monumentálně, malířsky iluzívně pojednaného dřevěného kříže, koncipovaného ovšem v diagonále (dramatizace) — se nachází v prvním prostorovém plánu, kdežto druhý plán — pozadí — je prostředí blízké neklidné abstrakci, jakýsi symbol vnějšího světa, atribut chaosu či atomizovaného bytí. Kříž jako symbol člověka (lidské postavy) je hlavním tématem i dalšího autorova významného obrazu Ležící (2004). V jeho případě je pozadí ještě relativně klidovou sjednocenou zónou — barevně i formálně značně kompaktní. Objevují se však též další pozoruhodné kompozice postavené na prostorové dvojdimenzionalitě, jež těží z napětí mezi konkrétním a neurčitým (abstraktním), jako např. Jedním tahem těsně nad zemí (2005), anebo obrazy evokující existenciální, poetickému vnímání světa napřímené stavy člověka (Tam za tebou je noc, 2002, Dva andělé, 2005). Rovněž Noc (2006) patří k těm ze současných umělcových obrazových kompozic, které abstraktní formou zpřítomňují až jakýsi, pragmatismem dobových přístupů k životu zatracený, barokně spirituální prožitek nekonečna, který je autorovu přístupu ke světu zcela inherentní. Je zjevné, že malba se mu stala nezbytným prostředkem bytostné komunikace. Svým intenzívním viděním tématu zjevuje to, co naše laické vidění považuje za neviditelné, co ale existuje jako nezbytnost, jako duchovní tkanivo našeho života, jako podstatný integrační prvek lidského bytí.</p>

<hr/>

<p><sup>1</sup> oldřich tichý, obrazy, Státní galerie ve Zlíně, foyer Městského divadla ve Zlíně, 1993 (úvodní text v katalogu Jana Šálková).</p>
<p><sup>2</sup> Oldřich Tichý byl svými pracemi zastoupen, vedle výstav přírůstků uměleckých sbírek a různě koncipovaných stálých expozic galerie, i na výstavě Ze současné tvorby — 90. léta ve zlínském Domě umění, kterou pořádala Státní galerie ve Zlíně (1995), a na všech čtyřech trienále Nový zlínský salon (1996, 1999, 2002, 2005).</p>
<p><sup>3</sup> Některá významná díla, zejména z dřívějších období, jsou ale v současnosti již zcela mimo dosah autora, v soukromých sbírkách, vesměs v zahraničí, a nemohla být proto uplatněna ani v expozici naší výstavy.</p>
<p><sup>4</sup> Prostředí na pražské avu v 80. letech 20. století patrně nebylo příliš liberální. Sám Oldřich Tichý na svá akademická studia vzpomíná s despektem: „Začal jsem figurami a ve čtvrťáku jsem už dělal abstraktní obrazy. To se ale profesorskému sboru moc nelíbilo, tak mě donutili dělat klasické disciplíny — akt, portrét, krajinu a zátiší, které jsem si nakonec vybral pro další práci . . .“</p>
<p>Náhody neexistují, rozhovor radana wagnera s oldřichem tichým. In: Já a Ty. Katalog výstavy Oldřicha Tichého, Galerie Václava Špály v Praze, 1993, nestr.</p>
<p><sup>5</sup> Již v roce 2003 proběhla pod názvem Já a Ty dokonce dosud nejvýznamnější přehlídka autorovy tvorby v Galerii Václava Špály. Viz pozn. č. 4.</p>


HTML;
